-- Oracle schema tham khảo cho 3 sheet đặc tả.
-- Có thể đổi tên bảng/cột để khớp schema doanh nghiệp thực tế.
CREATE TABLE CLAIM_GENERAL (
  ID NUMBER(10) PRIMARY KEY,
  MA_DON_VI VARCHAR2(10) NOT NULL,
  TEN_DON_VI VARCHAR2(100) NOT NULL,
  MA_KHU_VUC VARCHAR2(20) NOT NULL,
  TEN_KHU_VUC VARCHAR2(100) NOT NULL,
  BIEN_SO VARCHAR2(20) NOT NULL,
  NGAY_NHAP DATE NOT NULL,
  NGAY_NHAP_CALL DATE,
  SO_HOP_DONG VARCHAR2(50) NOT NULL,
  TINH_TRANG VARCHAR2(30) NOT NULL,
  NGAY_QUYET_DINH DATE,
  NGAY_XAY_RA DATE NOT NULL,
  NGAY_THONG_BAO DATE NOT NULL,
  SO_HO_SO VARCHAR2(50) NOT NULL UNIQUE,
  MA_GDV VARCHAR2(30),
  GIA_TRI_BH NUMBER(18,2) DEFAULT 0 NOT NULL,
  CONSTRAINT CK_CLAIM_NOTIFY_DATE CHECK (NGAY_THONG_BAO >= NGAY_XAY_RA)
);
CREATE SEQUENCE CLAIM_GENERAL_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;

CREATE TABLE VEHICLE_POLICY (
  ID NUMBER(10) PRIMARY KEY,
  SO_HOP_DONG VARCHAR2(50) NOT NULL UNIQUE,
  SO_DON_BAO_HIEM VARCHAR2(50) NOT NULL UNIQUE,
  MA_DON_VI VARCHAR2(10) NOT NULL,
  NGAY_CAP_DON DATE NOT NULL,
  MA_KHACH_HANG VARCHAR2(50),
  TEN_CHU_XE VARCHAR2(200) NOT NULL,
  LOAI_KHACH_HANG VARCHAR2(20) DEFAULT 'CA_NHAN' NOT NULL,
  SO_GIAY_TO VARCHAR2(50) NOT NULL,
  DIEN_THOAI VARCHAR2(30), EMAIL VARCHAR2(200), DIA_CHI VARCHAR2(500),
  BIEN_SO VARCHAR2(20) NOT NULL,
  SO_KHUNG VARCHAR2(50) NOT NULL UNIQUE,
  SO_MAY VARCHAR2(50) NOT NULL,
  NHAN_HIEU VARCHAR2(100) NOT NULL,
  DONG_XE VARCHAR2(100),
  NAM_SAN_XUAT NUMBER(4),
  MUC_DICH_SU_DUNG VARCHAR2(100),
  SO_CHO NUMBER(3), TRONG_TAI NUMBER(12,2),
  HIEU_LUC_TU DATE NOT NULL, HIEU_LUC_DEN DATE NOT NULL,
  PHAM_VI_BAO_HIEM VARCHAR2(1000) NOT NULL,
  NGOAI_TE VARCHAR2(10) DEFAULT 'VND' NOT NULL,
  GIA_TRI_XE NUMBER(18,2) DEFAULT 0 NOT NULL,
  SO_TIEN_BAO_HIEM NUMBER(18,2) DEFAULT 0 NOT NULL,
  PHI_TRUOC_THUE NUMBER(18,2) DEFAULT 0 NOT NULL,
  THUE_GTGT NUMBER(18,2) DEFAULT 0 NOT NULL,
  TONG_PHI NUMBER(18,2) DEFAULT 0 NOT NULL,
  MUC_KHAU_TRU NUMBER(18,2) DEFAULT 0 NOT NULL,
  KENH_KHAI_THAC VARCHAR2(50), MA_DAI_LY VARCHAR2(50), CAN_BO_CAP_DON VARCHAR2(50),
  TRANG_THAI VARCHAR2(20) DEFAULT 'NHAP' NOT NULL,
  GHI_CHU VARCHAR2(1000),
  NGAY_TAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  NGAY_CAP_NHAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT CK_POLICY_PERIOD CHECK (HIEU_LUC_DEN > HIEU_LUC_TU),
  CONSTRAINT CK_POLICY_YEAR CHECK (NAM_SAN_XUAT IS NULL OR NAM_SAN_XUAT BETWEEN 1900 AND 2100),
  CONSTRAINT CK_POLICY_AMOUNT CHECK (GIA_TRI_XE >= 0 AND SO_TIEN_BAO_HIEM >= 0 AND TONG_PHI >= 0),
  CONSTRAINT CK_POLICY_STATUS CHECK (TRANG_THAI IN ('NHAP','CHO_DUYET','DA_CAP','HUY','HET_HIEU_LUC'))
);
CREATE SEQUENCE VEHICLE_POLICY_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE INDEX IX_VEHICLE_POLICY_LOOKUP ON VEHICLE_POLICY(BIEN_SO, TEN_CHU_XE, TRANG_THAI, HIEU_LUC_DEN);

CREATE TABLE CLAIM_LOSS_PAYMENT (
  CLAIM_ID NUMBER(10) PRIMARY KEY REFERENCES CLAIM_GENERAL(ID) ON DELETE CASCADE,
  MA_NGUYEN_NHAN VARCHAR2(30) NOT NULL,
  MA_HANH_VI VARCHAR2(30),
  MA_KHU_VUC VARCHAR2(30) NOT NULL,
  MA_SU_KIEN VARCHAR2(100) NOT NULL,
  CV_TBTN_YCB VARCHAR2(100),
  GIA_TRI_XE_GCN NUMBER(18,2),
  DIEN_BIEN VARCHAR2(2000) NOT NULL,
  MO_TA_NGUYEN_NHAN VARCHAR2(2000) NOT NULL,
  MO_TA_HAU_QUA VARCHAR2(2000) NOT NULL,
  MA_GARA VARCHAR2(100), TEN_GARA VARCHAR2(500), PHONE_GARA VARCHAR2(50), EMAIL_GARA VARCHAR2(500),
  THANH_TOAN_QUA_GARA NUMBER(1) DEFAULT 0 NOT NULL,
  DOI_QUY_HIEP_HOI NUMBER(1) DEFAULT 0 NOT NULL
);
CREATE TABLE CLAIM_COVERAGE (
  ID NUMBER(10) PRIMARY KEY, CLAIM_ID NUMBER(10) NOT NULL REFERENCES CLAIM_GENERAL(ID) ON DELETE CASCADE,
  LOAI_HINH VARCHAR2(30), NGOAI_TE VARCHAR2(10), TIEN_BAO_HIEM NUMBER(18,2), TY_LE_TT NUMBER(8,2) DEFAULT 0 NOT NULL, TIEN_TT NUMBER(18,2), KHAU_TRU NUMBER(18,2), TIEN_BOI_THUONG NUMBER(18,2), THUE NUMBER(18,2)
);
CREATE TABLE CLAIM_BENEFICIARY (ID NUMBER(10) PRIMARY KEY, CLAIM_ID NUMBER(10) NOT NULL REFERENCES CLAIM_GENERAL(ID) ON DELETE CASCADE, MA VARCHAR2(100), TEN VARCHAR2(500), NGOAI_TE VARCHAR2(10), SO_TIEN NUMBER(18,2) DEFAULT 0 NOT NULL);
CREATE TABLE CLAIM_THIRD_PARTY (ID NUMBER(10) PRIMARY KEY, CLAIM_ID NUMBER(10) NOT NULL REFERENCES CLAIM_GENERAL(ID) ON DELETE CASCADE, TEN VARCHAR2(500), NGOAI_TE VARCHAR2(10), SO_TIEN NUMBER(18,2));

CREATE TABLE CLAIM_QUOTE (
  CLAIM_ID NUMBER(10) PRIMARY KEY REFERENCES CLAIM_GENERAL(ID) ON DELETE CASCADE,
  KIEU_DUYET VARCHAR2(50), GIA_TRI_THUC_TE NUMBER(18,2), NGAY_TRINH DATE, LY_DO_GIAM_TRU VARCHAR2(500),
  TONG_THAY_THE NUMBER(18,2), TONG_THAY_THE_DB NUMBER(18,2), TONG_SUA_CHUA NUMBER(18,2), TONG_SON NUMBER(18,2), TONG_CONG NUMBER(18,2), TONG_CAU_KEO NUMBER(18,2),
  GG_THAY_THE NUMBER(8,2), GG_SUA_CHUA NUMBER(8,2), GG_SON NUMBER(8,2), KHAU_HAO_THAY_THE NUMBER(8,2), KHAU_HAO_DB NUMBER(8,2),
  TL_GIA_TRI_THAM_GIA NUMBER(8,2), TL_PHI_THAM_GIA NUMBER(8,2), SO_VU_KHAU_TRU NUMBER(10), MUC_KHAU_TRU NUMBER(18,2), GIAM_TRU_BT NUMBER(8,2), CHIA_SE_RUI_RO NUMBER(8,2),
  KHACH_HANG_THANH_TOAN NUMBER(18,2), TONG_DUYET_GIA NUMBER(18,2), CHECKER VARCHAR2(30),
  CHI_PHI_CAN_THIET_HOP_LY NUMBER(18,2) DEFAULT 0 NOT NULL, KHAU_TRU_RIENG_DKBS NUMBER(18,2) DEFAULT 0 NOT NULL,
  LOAI_BOI_THUONG VARCHAR2(30) DEFAULT 'Bộ phận' NOT NULL, THIET_HAI_NGOAI_PHAM_VI NUMBER(18,2) DEFAULT 0 NOT NULL,
  GG_CONG NUMBER(8,2) DEFAULT 0 NOT NULL
);
CREATE TABLE CLAIM_QUOTE_ITEM (
  ID NUMBER(10) PRIMARY KEY, CLAIM_ID NUMBER(10) NOT NULL REFERENCES CLAIM_GENERAL(ID) ON DELETE CASCADE,
  MA_PHU_TUNG VARCHAR2(30), TEN_PHU_TUNG VARCHAR2(500), SO_LUONG NUMBER(10), THIET_HAI VARCHAR2(500), KICH_THUOC VARCHAR2(100), PHUONG_AN VARCHAR2(50), LOAI_PT VARCHAR2(50), GIA_PT NUMBER(18,2), SON NUMBER(18,2), CONG NUMBER(18,2)
);
CREATE TABLE CLAIM_QUOTE_DISCOUNT (
  CLAIM_ID NUMBER(10) PRIMARY KEY REFERENCES CLAIM_GENERAL(ID) ON DELETE CASCADE,
  GG_THAY_THE_DB NUMBER(8,2) DEFAULT 0 NOT NULL,
  GG_CAU_KEO NUMBER(8,2) DEFAULT 0 NOT NULL,
  SO_TIEN_GIAM_TRU_BT NUMBER(18,2) DEFAULT 0 NOT NULL
);
