-- Run with a MySQL 8 administrative account.
CREATE DATABASE IF NOT EXISTS claim_car
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'claim_car_app'@'localhost' IDENTIFIED BY 'CHANGE_ME';
GRANT SELECT, INSERT, UPDATE, DELETE ON claim_car.* TO 'claim_car_app'@'localhost';

USE claim_car;

CREATE TABLE IF NOT EXISTS CLAIM_GENERAL (
  ID INT NOT NULL AUTO_INCREMENT,
  MA_DON_VI VARCHAR(10) NOT NULL,
  TEN_DON_VI VARCHAR(100) NOT NULL,
  MA_KHU_VUC VARCHAR(20) NOT NULL,
  TEN_KHU_VUC VARCHAR(100) NOT NULL,
  BIEN_SO VARCHAR(20) NOT NULL,
  NGAY_NHAP DATETIME NOT NULL,
  NGAY_NHAP_CALL DATETIME NULL,
  SO_HOP_DONG VARCHAR(50) NOT NULL,
  TINH_TRANG VARCHAR(30) NOT NULL,
  NGAY_QUYET_DINH DATETIME NULL,
  NGAY_XAY_RA DATETIME NOT NULL,
  NGAY_THONG_BAO DATETIME NOT NULL,
  SO_HO_SO VARCHAR(50) NOT NULL,
  MA_GDV VARCHAR(30) NULL,
  GIA_TRI_BH DECIMAL(18,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_CLAIM_GENERAL_SO_HO_SO (SO_HO_SO),
  KEY IX_CLAIM_GENERAL_SEARCH (BIEN_SO, SO_HOP_DONG, TINH_TRANG),
  CONSTRAINT CK_CLAIM_NOTIFY_DATE CHECK (NGAY_THONG_BAO >= NGAY_XAY_RA)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS VEHICLE_POLICY (
  ID INT NOT NULL AUTO_INCREMENT,
  SO_HOP_DONG VARCHAR(50) NOT NULL,
  SO_DON_BAO_HIEM VARCHAR(50) NOT NULL,
  MA_DON_VI VARCHAR(10) NOT NULL,
  NGAY_CAP_DON DATETIME NOT NULL,
  MA_KHACH_HANG VARCHAR(50) NULL,
  TEN_CHU_XE VARCHAR(200) NOT NULL,
  LOAI_KHACH_HANG VARCHAR(20) NOT NULL DEFAULT 'CA_NHAN',
  SO_GIAY_TO VARCHAR(50) NOT NULL,
  DIEN_THOAI VARCHAR(30) NULL,
  EMAIL VARCHAR(200) NULL,
  DIA_CHI VARCHAR(500) NULL,
  BIEN_SO VARCHAR(20) NOT NULL,
  SO_KHUNG VARCHAR(50) NOT NULL,
  SO_MAY VARCHAR(50) NOT NULL,
  NHAN_HIEU VARCHAR(100) NOT NULL,
  DONG_XE VARCHAR(100) NULL,
  NAM_SAN_XUAT SMALLINT NULL,
  MUC_DICH_SU_DUNG VARCHAR(100) NULL,
  SO_CHO SMALLINT NULL,
  TRONG_TAI DECIMAL(12,2) NULL,
  HIEU_LUC_TU DATETIME NOT NULL,
  HIEU_LUC_DEN DATETIME NOT NULL,
  PHAM_VI_BAO_HIEM VARCHAR(1000) NOT NULL,
  NGOAI_TE VARCHAR(10) NOT NULL DEFAULT 'VND',
  GIA_TRI_XE DECIMAL(18,2) NOT NULL DEFAULT 0,
  SO_TIEN_BAO_HIEM DECIMAL(18,2) NOT NULL DEFAULT 0,
  PHI_TRUOC_THUE DECIMAL(18,2) NOT NULL DEFAULT 0,
  THUE_GTGT DECIMAL(18,2) NOT NULL DEFAULT 0,
  TONG_PHI DECIMAL(18,2) NOT NULL DEFAULT 0,
  MUC_KHAU_TRU DECIMAL(18,2) NOT NULL DEFAULT 0,
  KENH_KHAI_THAC VARCHAR(50) NULL,
  MA_DAI_LY VARCHAR(50) NULL,
  CAN_BO_CAP_DON VARCHAR(50) NULL,
  TRANG_THAI VARCHAR(20) NOT NULL DEFAULT 'NHAP',
  GHI_CHU VARCHAR(1000) NULL,
  NGAY_TAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NGAY_CAP_NHAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_VEHICLE_POLICY_CONTRACT (SO_HOP_DONG),
  UNIQUE KEY UK_VEHICLE_POLICY_NUMBER (SO_DON_BAO_HIEM),
  UNIQUE KEY UK_VEHICLE_POLICY_VIN (SO_KHUNG),
  KEY IX_VEHICLE_POLICY_LOOKUP (BIEN_SO, TEN_CHU_XE, TRANG_THAI, HIEU_LUC_DEN),
  CONSTRAINT CK_POLICY_PERIOD CHECK (HIEU_LUC_DEN > HIEU_LUC_TU),
  CONSTRAINT CK_POLICY_YEAR CHECK (NAM_SAN_XUAT IS NULL OR NAM_SAN_XUAT BETWEEN 1900 AND 2100),
  CONSTRAINT CK_POLICY_AMOUNT CHECK (GIA_TRI_XE >= 0 AND SO_TIEN_BAO_HIEM >= 0 AND TONG_PHI >= 0),
  CONSTRAINT CK_POLICY_STATUS CHECK (TRANG_THAI IN ('NHAP','CHO_DUYET','DA_CAP','HUY','HET_HIEU_LUC'))
) ENGINE=InnoDB;
