-- Run with a MySQL 8 administrative account.
CREATE DATABASE IF NOT EXISTS claim_car
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'claim_car_app'@'localhost' IDENTIFIED BY 'CHANGE_ME';
GRANT SELECT, INSERT, UPDATE, DELETE ON claim_car.* TO 'claim_car_app'@'localhost';

USE claim_car;

CREATE TABLE IF NOT EXISTS CLAIM_GENERAL (
  ID INT NOT NULL AUTO_INCREMENT,
  MA_DON_VI VARCHAR(10) NOT NULL,
  TEN_DON_VI VARCHAR(100) NOT NULL,
  MA_KHU_VUC VARCHAR(20) NOT NULL,
  TEN_KHU_VUC VARCHAR(100) NOT NULL,
  BIEN_SO VARCHAR(20) NOT NULL,
  NGAY_NHAP DATETIME NOT NULL,
  NGAY_NHAP_CALL DATETIME NULL,
  SO_HOP_DONG VARCHAR(50) NOT NULL,
  TINH_TRANG VARCHAR(30) NOT NULL,
  NGAY_QUYET_DINH DATETIME NULL,
  NGAY_XAY_RA DATETIME NOT NULL,
  NGAY_THONG_BAO DATETIME NOT NULL,
  SO_HO_SO VARCHAR(50) NOT NULL,
  MA_GDV VARCHAR(30) NULL,
  GIA_TRI_BH DECIMAL(18,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_CLAIM_GENERAL_SO_HO_SO (SO_HO_SO),
  KEY IX_CLAIM_GENERAL_SEARCH (BIEN_SO, SO_HOP_DONG, TINH_TRANG),
  CONSTRAINT CK_CLAIM_NOTIFY_DATE CHECK (NGAY_THONG_BAO >= NGAY_XAY_RA)
) ENGINE=InnoDB;
